sequenceDiagram
    actor C as Client
    participant S as Server

    C->>S: Ask the server for the file's folder's metadata
    S-->>C: Send the file's folder's metadata

    C->>C: Decrypt the folder's encrypted key with the user's private key