sequenceDiagram
    actor C as Client
    participant S as Server

    note over C,S: Assume the user has already logged in <br> and is in possession of the folder key

    C->>S: Ask the server for the file metadata
    S-->>C: Send the file metadata

    C->>C: Derive the file's key from the folder's key <br> and the file's nonce

    C->>C: Decrypt the file's encrypted name with <br> the file's decrypted key and the name nonce
    C->>C: Decrypt the file's encrypted data with <br> the file's decrypted key and the data nonce