sequenceDiagram
    actor C as Client
    participant S as Server

    note over C,S: Assume the user has already logged in <br> and is in possession of the parent folder key

    C->>C: Generate a random key nonce
    C->>C: Derive a new folder key from the parent folder key and the key nonce
    C->>C: Encrypt the new folder's key using the user's public key

    C->>C: Generate a random name nonce
    C->>C: Encrypt the folder name using the <br> new folder's key and the name nonce

    C->>S: Ask server to create a new folder with the encrypted key, <br> the encrypted folder name and the nonces