sequenceDiagram
    actor C as Client
    participant S as Server

    C->>S: Ask for the folder's encrypted key and the folder's seed
    S-->>C: Send the folder's encrypted key and the folder's seed

    C->>C: Decrypt the folder's encrypted key with the user's private key

    C->>C: Genereate 3 random nonces (nonce_data, nonce_key, nonce_name)

    C->>C: Generate a random file key

    C->>C: Encrypt the file's data with the key and the nonce_data using AES-GCM
    C->>C: Encrypt the file's name with the key and the nonce_name using AES-GCM

    C->>C: Encrypt the file key with the folder's decrypted key and nonce_key using AES-GCM

    C->>S: Send the encrypted file's data (with tag), the encrypted file's name (with tag), the 3 nonces and the encrypted file key