version: "3.8"

services:
  server:
    build: ./server
    volumes:
      - ./server/data/:/app/data
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "4242:4242"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/out:/etc/nginx/certs:ro # Edit here to point to your certs