#ifndef EFFECTIVE_OCTO_SYSTEM_CONNECTIONSTATUS_H
#define EFFECTIVE_OCTO_SYSTEM_CONNECTIONSTATUS_H


enum ConnectionStatus
{
    AUTHENTICATED,
    UNAUTHENTICATED,
    DISCONNECTED
};


#endif //EFFECTIVE_OCTO_SYSTEM_CONNECTIONSTATUS_H
